param([Parameter(Mandatory=$true)][string]$BookPath)
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem

# Curated contiguous paragraphs, not keyword snippets. The EPUB stays outside
# the repository; only these selected passages become a generated source module.
$selections=@(
  @{Id='TT-01';Book='1888';Chapter='c04';Paragraphs=@(243)},
  @{Id='TT-02';Book='1918';Chapter='c11';Find='The skimmer flies low over the valley, and de Soya identifies'},
  @{Id='TT-03';Book='1895';Chapter='c03';Paragraphs=@(26)},
  @{Id='TT-04';Book='1895';Chapter='c16';Paragraphs=@(68)},
  @{Id='TT-05';Book='1895';Chapter='c05';Paragraphs=@(9)},
  @{Id='TT-06';Book='1895';Chapter='c16';Paragraphs=@(70,71)},
  @{Id='TT-07';Book='1895';Chapter='c03';Paragraphs=@(29)},
  @{Id='TT-29';Book='1888';Chapter='c04';Paragraphs=@(245)},
  @{Id='TT-20';Book='1888';Chapter='c01';Paragraphs=@(28,29,30)},
  @{Id='TT-21';Book='1888';Chapter='c01';Paragraphs=@(27)},
  @{Id='TT-22';Book='1888';Chapter='c01';Paragraphs=@(25,26)},
  @{Id='TT-23';Book='1888';Chapter='c01';Paragraphs=@(5)},
  @{Id='TT-24';Book='1888';Chapter='c01';Paragraphs=@(19,20)},
  @{Id='TT-25';Book='1888';Chapter='c01';Paragraphs=@(21,22,23)},
  @{Id='TT-26';Book='1888';Chapter='c01';Paragraphs=@(6)},
  @{Id='TT-27';Book='1895';Chapter='c16';Paragraphs=@(4)},
  @{Id='TT-28';Book='1895';Chapter='c03';Paragraphs=@(24,25)},
  @{Id='TT-31';Book='1888';Chapter='c03';Paragraphs=@(477)},
  @{Id='welcome';Book='1888';Chapter='epl';Paragraphs=@(23)},
  @{Id='TT-01:research';Book='1888';Chapter='c04';Paragraphs=@(244)},
  @{Id='TT-01:geometry';Book='1888';Chapter='c04';Paragraphs=@(249)},
  @{Id='TT-03:fractures';Book='1895';Chapter='c16';Paragraphs=@(69)},
  @{Id='TT-05:night';Book='1895';Chapter='c03';Paragraphs=@(85,86)},
  @{Id='TT-06:labyrinth';Book='1895';Chapter='c34';Paragraphs=@(117)},
  @{Id='TT-07:fire';Book='1895';Chapter='c03';Paragraphs=@(3)},
  @{Id='TT-29:research';Book='1888';Chapter='c04';Paragraphs=@(244)},
  @{Id='TT-28:wind';Book='1895';Chapter='c42';Paragraphs=@(137,138)},
  @{Id='TT-31:memory';Book='1888';Chapter='prl';Paragraphs=@(25)},
  @{Id='TT-33';Book='1888';Chapter='c02';Paragraphs=@(28,29)},
  @{Id='TT-33:flight';Book='1895';Chapter='c35';Paragraphs=@(64,65,66,67)}
)
$titles=@{'1888'='Hyperion';'1895'='The Fall of Hyperion';'1918'='Endymion'}
$passages=[ordered]@{}
$zip=[IO.Compression.ZipFile]::OpenRead((Resolve-Path -LiteralPath $BookPath))
try {
  foreach($selection in $selections) {
    $document='OEBPS/Simm_978030778'+$selection.Book+'_epub_'+$selection.Chapter+'_r1.htm'
    $entry=$zip.GetEntry($document)
    if(!$entry){throw "Missing source chapter: $document"}
    $reader=[IO.StreamReader]::new($entry.Open())
    try {$html=$reader.ReadToEnd()} finally {$reader.Dispose()}
    $paragraphs=@([regex]::Matches($html,'(?s)<p\b[^>]*>.*?</p>') | ForEach-Object {
      ([Net.WebUtility]::HtmlDecode(($_.Value -replace '<[^>]+>','')) -replace '\s+',' ').Trim()
    })
    $indices=$selection.Paragraphs
    if($selection.Find) {
      $indices=@(0..($paragraphs.Count-1) | Where-Object {$paragraphs[$_].StartsWith($selection.Find)})
      if($indices.Count -ne 1){throw "Expected one source paragraph for $($selection.Id)"}
    }
    $text=($indices | ForEach-Object {$paragraphs[$_]}) -join "`n`n"
    if($text.Length -lt 200){throw "Incomplete context for $($selection.Id)"}
    $chapter=switch($selection.Chapter){'epl'{'Epilogue'} 'prl'{'Prologue'} default{'Chapter '+[int]$selection.Chapter.Substring(1)}}
    $passages[$selection.Id]=[ordered]@{text=$text;source=('Dan Simmons · '+$titles[$selection.Book]+' · '+$chapter);document=$document;paragraphs=@($indices)}
  }
} finally {$zip.Dispose()}
$json=$passages | ConvertTo-Json -Depth 5
$module=@"
// Generated by scripts/import-time-tombs-excerpts.ps1 from the user's local EPUB.
// Complete, contiguous source paragraphs; only HTML/whitespace is normalized.
// Provenance is retained for verification. Do not replace book text with paraphrase.
export const BOOK_SOURCE='Dan Simmons · Hyperion Cantos';
export const BOOK_PASSAGES=$json;
export const BOOK_EXCERPTS=Object.fromEntries(Object.entries(BOOK_PASSAGES).filter(([id])=>id!=='welcome'&&!id.includes(':')).map(([id,p])=>[id,p.text]));
export const BOOK_SOURCES=Object.fromEntries(Object.entries(BOOK_PASSAGES).map(([id,p])=>[id,p.source]));
export const BOOK_COLLECTIONS=Object.fromEntries(Object.keys(BOOK_EXCERPTS).map(id=>[id,Object.entries(BOOK_PASSAGES).filter(([key])=>key===id||key.startsWith(id+':')).map(([,p])=>({excerpt:p.text,source:p.source}))]));
export const VALLEY_EXCERPT=BOOK_PASSAGES.welcome.text;
export const VALLEY_SOURCE=BOOK_PASSAGES.welcome.source;
"@
$destination=Join-Path $PSScriptRoot '../src/time-tombs/book-excerpts.js'
[IO.File]::WriteAllText($destination,($module -replace "`r`n","`n")+"`n",[Text.UTF8Encoding]::new($false))
Write-Output "Imported $($passages.Count) context passages with book/chapter provenance. The EPUB was not copied."
